// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAuS9rLd8AVf3vofhN3yfvuyrv3XD2zAiw',
//     appId: '1:380379696138:web:a7771b6fe4dd9c384ba3f3',
//     messagingSenderId: '380379696138',
//     projectId: 'dent-48478',
//     authDomain: 'dent-48478.firebaseapp.com',
//     storageBucket: 'dent-48478.firebasestorage.app',
//     measurementId: 'G-8J3LZK2EXP',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAqkCnNJCIQUx08YiOn3sdaMRM-ELU1m6k',
//     appId: '1:380379696138:android:df87dd3f29f2ac2f4ba3f3',
//     messagingSenderId: '380379696138',
//     projectId: 'dent-48478',
//     storageBucket: 'dent-48478.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCi3rU_bIzhX9LeXmTiFBS558V0id8KvRo',
//     appId: '1:380379696138:ios:ad39f6132b1bfcc74ba3f3',
//     messagingSenderId: '380379696138',
//     projectId: 'dent-48478',
//     storageBucket: 'dent-48478.firebasestorage.app',
//     iosBundleId: 'com.example.dent',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCi3rU_bIzhX9LeXmTiFBS558V0id8KvRo',
//     appId: '1:380379696138:ios:ad39f6132b1bfcc74ba3f3',
//     messagingSenderId: '380379696138',
//     projectId: 'dent-48478',
//     storageBucket: 'dent-48478.firebasestorage.app',
//     iosBundleId: 'com.example.dent',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAuS9rLd8AVf3vofhN3yfvuyrv3XD2zAiw',
//     appId: '1:380379696138:web:41219278b0a282014ba3f3',
//     messagingSenderId: '380379696138',
//     projectId: 'dent-48478',
//     authDomain: 'dent-48478.firebaseapp.com',
//     storageBucket: 'dent-48478.firebasestorage.app',
//     measurementId: 'G-KTSYCTWYBR',
//   );
// }
